project:
  type: website
  preview:
    port: 4200
    browser: true

website:
  title: "Vishal Katti"
  site-url: https://learnwith.vishalkatti.com
  description: "Learn With Katti"
  favicon: "VK Logo.png"
  navbar:
    logo: "VK Logo.png"
    search: true
    right:
      - text: "About the Instructor"
        file: about.qmd
      - text: "Courses"
        file: index.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/vishalkatti
      - icon: twitter
        href: https://twitter.com/vishal_katti
      - icon: mastodon
        href: https://fosstodon.org/@vishalkatti
      - icon: rss
        file: index.xml
  page-footer: 
    left: Vishal Katti {{< fa regular copyright >}} 2024<br>made with 💖 and [Quarto](https://quarto.org)
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/vishalkatti
      - icon: twitter 
        href: https://twitter.com/vishal_katti
      - icon: mastodon
        href: https://fosstodon.org/@vishalkatti
        
  twitter-card: 
    title: "Learn With Katti"
    image: "VK Logo.png"
    creator: "@vishal_katti"
    site: "@vishal_katti"
    
  open-graph: true
format:
  html:
    theme: 
      light: litera
    toc: true
    highlight-style: arrow
    css: styles.css
    mainfont: Candara



